Salt version 3004
plus3it/watchmaker pull request #1903
Opened 2022-01-06 17:03 UTC by kumoy

2022-01-12 19:10 UTC, lorengordon commented on src/watchmaker/static/config.yaml
> +          url: https://watchmaker.cloudarmor.io/watchmaker/yum.defs/saltstack/salt/3004/salt-reposync-el7-python3.repo
while this works, prefer leaving out the leading "watchmaker" prefix

```suggestion
          url: https://watchmaker.cloudarmor.io/yum.defs/saltstack/salt/3004/salt-reposync-el7-python3.repo
```

2022-01-12 19:10 UTC, lorengordon commented on src/watchmaker/static/config.yaml
> +      installer_url: https://watchmaker.cloudarmor.io/watchmaker/repo/saltstack/salt/windows/Salt-Minion-3004-2-Py3-AMD64-Setup.exe
while this works, prefer leaving out the leading "watchmaker" prefix

```suggestion
      installer_url: https://watchmaker.cloudarmor.io/repo/saltstack/salt/windows/Salt-Minion-3004-2-Py3-AMD64-Setup.exe
```

2022-01-13 18:31 UTC, dwc0011 commented on src/watchmaker/workers/salt.py
> +        self.salt_call = self._get_salt_call()
Since the method is static now change this to SaltWindows._get_salt_call()

2022-01-26 15:32 UTC, lorengordon requested changes
One comment on the test name. And ideally, we'd have a second test, where isfile returns false, and checking the return value.

```
@patch("os.path.isfile", MagicMock(return_value=False))
```

2022-01-26 15:32 UTC, lorengordon commented on tests/test_saltworker.py
> +def test_windows_install_new():
Let's name this test something closer to what it is testing:

```suggestion
def test_windows_salt_call_new():
```

2022-01-26 23:37 UTC, lorengordon approved these changes

2022-01-26 23:37 UTC, lorengordon commented
go codebuild go

2022-01-31 14:02 UTC, lorengordon commented
go codebuild go

2022-02-01 18:57 UTC, kumoy commented
go codebuild go

2022-02-07 18:57 UTC, dwc0011 commented
go codebuild go

2022-02-23 21:26 UTC, dwc0011 commented
go codebuild go

2022-02-24 16:11 UTC, dwc0011 commented
go codebuild go

2022-03-01 21:39 UTC, lorengordon commented
go codebuild go

2022-03-01 22:29 UTC, lorengordon approved these changes
The updates to terrafirm are demonstrating that this is working! Hurray! 🚢

2022-03-01 22:44 UTC, merged